### ISSUE TITLE
Release under libre license

### ISSUE THREAD

**Issue by throwaway1037** [Wano-k/RPG-Paper-Maker#85]
Please may the project be released under a [libre](https://freedomdefined.org/Licenses) license?
Some OS distributions such as [Parabola](https://parabola.nu) cannot package software which are not libre.

I would personally recommend the GNU-AGPL-3.0-or-later license for source code.

**Comment by EgyLynx** [comment]
?? If it download at it easy, why you nneed do THAT even??

**Comment by throwaway1037** [comment]
That doesn't make any sense.

**Comment by ChiefTokenologist** [comment]
What's the status of this code? As in still operable, any updates? Recommendations

**Comment by Wano-k** [comment]
The project was initially under libre license. Due to legal issues with the particular conditions of selling, it was decided to switch to proprietary, but sitll opened code. You can check out the EULA here: [https://rpg-paper-maker.com/rpg-paper-maker-eula/](https://rpg-paper-maker.com/rpg-paper-maker-eula/).
